# Nome do workflow (aparece l치 na aba "A칞칫es")
name: Cobrinha dos Commits 游냀

# Quando esse fluxo vai rodar
on:
  schedule: # roda automaticamente todo dia 맙 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # permite rodar manualmente pelo bot칚o "Executar workflow"

jobs:
  build:
    runs-on: ubuntu-latest # servidor Linux onde vai rodar o job

    steps:
      # Primeiro passo: baixar o reposit칩rio
      - name: Baixar reposit칩rio
        uses: actions/checkout@v3

      # Segundo passo: gerar a anima칞칚o da cobrinha
      - name: Gerar anima칞칚o da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: biazz-codificador # <-- teu usu치rio do GitHub
          outputs: dist/github-contribution-grid-snake.svg # onde vai salvar o SVG

      # Terceiro passo: commitar o arquivo gerado no reposit칩rio
      - name: Subir resultado
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Cobrinha atualizada 游냀"
          add: "dist/github-contribution-grid-snake.svg"
